import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const CONTRACTORS = [
  {
    firstName: 'Marcus',   lastName: 'Webb',
    email: 'marcus.webb@buildmatch.dev',
    city: 'Austin', state: 'TX', zipCode: '78701',
    bio: 'Licensed general contractor with 18 years of experience in residential and commercial builds. Specializes in custom home construction and large-scale renovations across Central Texas.',
    specialties: ['GENERAL', 'ROOFING'],
    yearsExperience: 18, hourlyRateMin: 85, hourlyRateMax: 130,
    averageRating: 4.9, totalReviews: 47, completedJobs: 52,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    firstName: 'Diana',    lastName: 'Nguyen',
    email: 'diana.nguyen@buildmatch.dev',
    city: 'San Jose', state: 'CA', zipCode: '95101',
    bio: 'Master electrician certified in CA with expertise in smart home automation, solar panel integration, and commercial panel upgrades. Fully insured and licensed.',
    specialties: ['ELECTRICAL'],
    yearsExperience: 12, hourlyRateMin: 95, hourlyRateMax: 145,
    averageRating: 4.8, totalReviews: 63, completedJobs: 71,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    firstName: 'Terrell',  lastName: 'Brooks',
    email: 'terrell.brooks@buildmatch.dev',
    city: 'Atlanta', state: 'GA', zipCode: '30301',
    bio: 'Expert plumber specializing in full bathroom remodels, water heater installations, and emergency leak repairs. Available 24/7 for urgent jobs in metro Atlanta.',
    specialties: ['PLUMBING'],
    yearsExperience: 10, hourlyRateMin: 75, hourlyRateMax: 110,
    averageRating: 4.7, totalReviews: 38, completedJobs: 44,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/55.jpg',
  },
  {
    firstName: 'Sofia',    lastName: 'Reyes',
    email: 'sofia.reyes@buildmatch.dev',
    city: 'Miami', state: 'FL', zipCode: '33101',
    bio: 'HVAC specialist with over 14 years in residential and light commercial systems. Expert in energy-efficient AC installations, ductwork, and annual maintenance contracts.',
    specialties: ['HVAC'],
    yearsExperience: 14, hourlyRateMin: 80, hourlyRateMax: 120,
    averageRating: 4.6, totalReviews: 29, completedJobs: 33,
    isAvailable: false,
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    firstName: 'James',    lastName: 'Okafor',
    email: 'james.okafor@buildmatch.dev',
    city: 'Dallas', state: 'TX', zipCode: '75201',
    bio: 'Certified roofing contractor with experience in shingle, metal, and flat roof systems. Provides storm damage assessments and works directly with insurance companies.',
    specialties: ['ROOFING'],
    yearsExperience: 9, hourlyRateMin: 70, hourlyRateMax: 105,
    averageRating: 4.5, totalReviews: 22, completedJobs: 28,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/76.jpg',
  },
  {
    firstName: 'Priya',    lastName: 'Sharma',
    email: 'priya.sharma@buildmatch.dev',
    city: 'Seattle', state: 'WA', zipCode: '98101',
    bio: 'Flooring installation expert with skills in hardwood, LVP, tile, and epoxy garage floors. Detailed craftsmanship and clean job sites every time.',
    specialties: ['FLOORING'],
    yearsExperience: 7, hourlyRateMin: 60, hourlyRateMax: 90,
    averageRating: 4.8, totalReviews: 41, completedJobs: 47,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    firstName: 'Carlos',   lastName: 'Mendoza',
    email: 'carlos.mendoza@buildmatch.dev',
    city: 'Phoenix', state: 'AZ', zipCode: '85001',
    bio: 'Interior and exterior painting professional. Specializes in color consultation, cabinet painting, and commercial repaint projects. EPA lead-safe certified.',
    specialties: ['PAINTING'],
    yearsExperience: 11, hourlyRateMin: 55, hourlyRateMax: 80,
    averageRating: 4.7, totalReviews: 55, completedJobs: 62,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/23.jpg',
  },
  {
    firstName: 'Aisha',    lastName: 'Johnson',
    email: 'aisha.johnson@buildmatch.dev',
    city: 'Charlotte', state: 'NC', zipCode: '28201',
    bio: 'Licensed landscaper and outdoor design specialist. Creates custom irrigation systems, hardscaping, retaining walls, and seasonal plantings for residential and HOA communities.',
    specialties: ['LANDSCAPING'],
    yearsExperience: 8, hourlyRateMin: 65, hourlyRateMax: 95,
    averageRating: 4.9, totalReviews: 34, completedJobs: 39,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/29.jpg',
  },
  {
    firstName: 'Ryan',     lastName: 'Kowalski',
    email: 'ryan.kowalski@buildmatch.dev',
    city: 'Chicago', state: 'IL', zipCode: '60601',
    bio: 'General contractor focused on basement finishing, kitchen remodels, and additions. Strong project management background — on-time and on-budget delivery every project.',
    specialties: ['GENERAL', 'FLOORING', 'PAINTING'],
    yearsExperience: 15, hourlyRateMin: 90, hourlyRateMax: 140,
    averageRating: 4.6, totalReviews: 27, completedJobs: 31,
    isAvailable: false,
    photo: 'https://randomuser.me/api/portraits/men/41.jpg',
  },
  {
    firstName: 'Monique',  lastName: 'Trahan',
    email: 'monique.trahan@buildmatch.dev',
    city: 'New Orleans', state: 'LA', zipCode: '70112',
    bio: 'Demolition specialist with expertise in selective interior demolition, structural removal, and site prep. Licensed and carries full liability insurance.',
    specialties: ['DEMOLITION', 'GENERAL'],
    yearsExperience: 13, hourlyRateMin: 75, hourlyRateMax: 115,
    averageRating: 4.4, totalReviews: 18, completedJobs: 24,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/52.jpg',
  },
  {
    firstName: 'Derek',    lastName: 'Simmons',
    email: 'derek.simmons@buildmatch.dev',
    city: 'Denver', state: 'CO', zipCode: '80201',
    bio: 'Multi-trade contractor specializing in electrical and HVAC systems for new construction. Over 16 years building high-efficiency homes in the Colorado Front Range.',
    specialties: ['ELECTRICAL', 'HVAC'],
    yearsExperience: 16, hourlyRateMin: 100, hourlyRateMax: 150,
    averageRating: 4.8, totalReviews: 36, completedJobs: 41,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    firstName: 'Leila',    lastName: 'Farouk',
    email: 'leila.farouk@buildmatch.dev',
    city: 'Houston', state: 'TX', zipCode: '77001',
    bio: 'Residential plumber with deep experience in slab leak detection, repipe projects, and bathroom additions. Trusted by over 300 Houston homeowners.',
    specialties: ['PLUMBING'],
    yearsExperience: 6, hourlyRateMin: 70, hourlyRateMax: 100,
    averageRating: 4.5, totalReviews: 19, completedJobs: 22,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/73.jpg',
  },
  {
    firstName: 'Nathan',   lastName: 'Pierce',
    email: 'nathan.pierce@buildmatch.dev',
    city: 'Portland', state: 'OR', zipCode: '97201',
    bio: 'Exterior and roofing specialist focused on Pacific Northwest weather-proofing. Expert in cedar shakes, standing-seam metal roofs, and waterproofing for older homes.',
    specialties: ['ROOFING', 'GENERAL'],
    yearsExperience: 20, hourlyRateMin: 80, hourlyRateMax: 125,
    averageRating: 4.9, totalReviews: 61, completedJobs: 68,
    isAvailable: false,
    photo: 'https://randomuser.me/api/portraits/men/88.jpg',
  },
  {
    firstName: 'Keisha',   lastName: 'Watts',
    email: 'keisha.watts@buildmatch.dev',
    city: 'Memphis', state: 'TN', zipCode: '38101',
    bio: 'Painting and flooring contractor with an eye for design. Offers full interior refresh packages — walls, trim, and floors — for landlords and homeowners preparing to sell.',
    specialties: ['PAINTING', 'FLOORING'],
    yearsExperience: 5, hourlyRateMin: 50, hourlyRateMax: 75,
    averageRating: 4.6, totalReviews: 24, completedJobs: 28,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/36.jpg',
  },
  {
    firstName: 'Paulo',    lastName: 'Alves',
    email: 'paulo.alves@buildmatch.dev',
    city: 'San Antonio', state: 'TX', zipCode: '78201',
    bio: 'Landscaping and outdoor living specialist. Builds custom pergolas, outdoor kitchens, fire pits, and pool-surround hardscaping. Bilingual (English/Spanish).',
    specialties: ['LANDSCAPING', 'GENERAL'],
    yearsExperience: 9, hourlyRateMin: 60, hourlyRateMax: 90,
    averageRating: 4.7, totalReviews: 31, completedJobs: 35,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/14.jpg',
  },
  {
    firstName: 'Grace',    lastName: 'Huang',
    email: 'grace.huang@buildmatch.dev',
    city: 'Las Vegas', state: 'NV', zipCode: '89101',
    bio: 'Commercial electrician specializing in tenant improvements, retail fit-outs, and parking lot lighting. Works with general contractors on new builds throughout Nevada.',
    specialties: ['ELECTRICAL'],
    yearsExperience: 10, hourlyRateMin: 90, hourlyRateMax: 135,
    averageRating: 4.8, totalReviews: 45, completedJobs: 50,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/81.jpg',
  },
  {
    firstName: 'Darius',   lastName: 'Hall',
    email: 'darius.hall@buildmatch.dev',
    city: 'Columbus', state: 'OH', zipCode: '43201',
    bio: 'Full-service HVAC contractor handling residential service calls, system replacements, and commercial refrigeration. EPA 608 certified, all major brands.',
    specialties: ['HVAC', 'ELECTRICAL'],
    yearsExperience: 12, hourlyRateMin: 85, hourlyRateMax: 125,
    averageRating: 4.5, totalReviews: 20, completedJobs: 25,
    isAvailable: false,
    photo: 'https://randomuser.me/api/portraits/men/49.jpg',
  },
  {
    firstName: 'Ingrid',   lastName: 'Larsson',
    email: 'ingrid.larsson@buildmatch.dev',
    city: 'Minneapolis', state: 'MN', zipCode: '55401',
    bio: 'Demolition and site prep contractor focused on residential teardowns, deck removal, and ADU site preparation. Fast, tidy, and licensed for hazardous material abatement.',
    specialties: ['DEMOLITION'],
    yearsExperience: 7, hourlyRateMin: 65, hourlyRateMax: 95,
    averageRating: 4.4, totalReviews: 14, completedJobs: 18,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/57.jpg',
  },
  {
    firstName: 'Victor',   lastName: 'Castillo',
    email: 'victor.castillo@buildmatch.dev',
    city: 'El Paso', state: 'TX', zipCode: '79901',
    bio: 'General contractor and project manager with 22 years building custom homes, ADUs, and commercial shell-buildings across West Texas and New Mexico.',
    specialties: ['GENERAL', 'ROOFING', 'PLUMBING'],
    yearsExperience: 22, hourlyRateMin: 95, hourlyRateMax: 145,
    averageRating: 4.9, totalReviews: 72, completedJobs: 80,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/men/62.jpg',
  },
  {
    firstName: 'Tanya',    lastName: 'Mitchell',
    email: 'tanya.mitchell@buildmatch.dev',
    city: 'Nashville', state: 'TN', zipCode: '37201',
    bio: 'Flooring and tile specialist with experience in luxury vinyl, porcelain tile, and natural stone. Works on high-end residential remodels and boutique commercial spaces.',
    specialties: ['FLOORING'],
    yearsExperience: 8, hourlyRateMin: 65, hourlyRateMax: 95,
    averageRating: 4.7, totalReviews: 33, completedJobs: 38,
    isAvailable: true,
    photo: 'https://randomuser.me/api/portraits/women/19.jpg',
  },
];

async function main() {
  console.log('Seeding 20 contractors...\n');

  const passwordHash = await bcrypt.hash('Contractor2026!', 12);

  for (const c of CONTRACTORS) {
    const user = await prisma.user.upsert({
      where: { email: c.email },
      update: {},
      create: {
        email: c.email,
        password: passwordHash,
        role: 'CONTRACTOR',
        firstName: c.firstName,
        lastName: c.lastName,
        isVerified: true,
        isActive: true,
      },
    });

    await prisma.contractorProfile.upsert({
      where: { userId: user.id },
      update: {
        bio: c.bio,
        specialties: c.specialties,
        yearsExperience: c.yearsExperience,
        city: c.city,
        state: c.state,
        zipCode: c.zipCode,
        hourlyRateMin: c.hourlyRateMin,
        hourlyRateMax: c.hourlyRateMax,
        averageRating: c.averageRating,
        totalReviews: c.totalReviews,
        completedJobs: c.completedJobs,
        isAvailable: c.isAvailable,
        portfolioImages: [c.photo],
      },
      create: {
        userId: user.id,
        bio: c.bio,
        specialties: c.specialties,
        yearsExperience: c.yearsExperience,
        city: c.city,
        state: c.state,
        zipCode: c.zipCode,
        hourlyRateMin: c.hourlyRateMin,
        hourlyRateMax: c.hourlyRateMax,
        averageRating: c.averageRating,
        totalReviews: c.totalReviews,
        completedJobs: c.completedJobs,
        isAvailable: c.isAvailable,
        portfolioImages: [c.photo],
      },
    });

    console.log(`  ✓ ${c.firstName} ${c.lastName} (${c.specialties.join(', ')}) — ${c.city}, ${c.state}`);
  }

  console.log('\n20 contractors seeded successfully.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
